### ISSUE TITLE
TypeError: session.reply is not a function

### ISSUE THREAD

**Issue by ummahusla** [Bottr-js/Bottr#16]
I was following the docs in order to setup the bot and suddenly I've encountered this error.

```
$ bottr-cli start
Mon, 10 Oct 2016 16:42:13 GMT body-parser deprecated undefined extended: provide extended option at node_modules\bottr\lib\bot.js:36:30
new websocket connection
new websocket connection
message_received event triggered
Missing error handler on `socket`.
TypeError: session.reply is not a function
    at Event.<anonymous> (C:\wamp\www\bottr\index.js:13:11)
    at Event.next (C:\wamp\www\bottr\node_modules\bottr\lib\event.js:16:14)
    at Event.triggerNext (C:\wamp\www\bottr\node_modules\bottr\lib\event.js:10:12)
    at Event.<anonymous> (C:\wamp\www\bottr\node_modules\bottr\lib\bot.js:22:5)
    at Event.next (C:\wamp\www\bottr\node_modules\bottr\lib\event.js:16:14)
    at EventEmitter.emit (C:\wamp\www\bottr\node_modules\bottr\lib\event-emitter.js:28:9)
    at Bot.trigger (C:\wamp\www\bottr\node_modules\bottr\lib\bot.js:49:26)
    at WebsocketClient.<anonymous> (C:\wamp\www\bottr\node_modules\bottr\lib\websocket-client.js:24:14)
    at emitOne (events.js:78:13)
    at Socket.emit (events.js:170:7)
    at Socket.onevent (C:\wamp\www\bottr\node_modules\socket.io\lib\socket.js:348:8)
    at Socket.onpacket (C:\wamp\www\bottr\node_modules\socket.io\lib\socket.js:308:12)
    at Client.ondecoded (C:\wamp\www\bottr\node_modules\socket.io\lib\client.js:194:14)
    at Decoder.Emitter.emit (C:\wamp\www\bottr\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (C:\wamp\www\bottr\node_modules\socket.io-parser\index.js:247:12)
    at Client.ondata (C:\wamp\www\bottr\node_modules\socket.io\lib\client.js:176:18)
```

**Comment by jcampbell05** [comment]
Looks like the old example code needs to be updated to be `send`, session keeps track of the conversation now.

**Comment by jcampbell05** [comment]
@ummahusla I've pushed a new version of `bottr-cli` let me know if `bottr-cli init` generates something that works.

**Comment by ummahusla** [comment]
@jcampbell05 Will do it in the evening 👍
